package commands

import (
	"fmt"
	"sort"
	"time"

	"github.com/spf13/cobra"
)

var dumpCmd = &cobra.Command{
	Use:   "dump",
	Short: "Generate a Yumfile from the current system state",
	Long: `Dump generates a Yumfile by listing all manually installed packages
and custom repositories from the system.`,
	RunE: runDump,
}

func init() {
	rootCmd.AddCommand(dumpCmd)
}

func runDump(cmd *cobra.Command, args []string) error {
	w := cmd.OutOrStdout()

	fmt.Fprintln(w, "# Yumfile generated by yum-bundle dump")
	fmt.Fprintln(w, "# Generated on:", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintln(w)

	fmt.Fprintln(w, "# --- Packages ---")
	packages, err := mgr.GetAllInstalledPackages()
	if err != nil {
		return fmt.Errorf("failed to list installed packages: %w", err)
	}

	sort.Strings(packages)
	for _, pkg := range packages {
		fmt.Fprintln(w, "yum", pkg)
	}

	repos, err := mgr.ListCustomRepos()
	if err != nil {
		return fmt.Errorf("failed to list custom repositories: %w", err)
	}
	if len(repos) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "# --- Repositories ---")
		for _, r := range repos {
			fmt.Fprintln(w, r.YumfileLine)
		}
	}

	return nil
}
